<style>
@media screen and (max-width: 900px) {
    .molvp-protection {
        position: absolute;
        display: none;
        z-index: 100;
        float: right;
        top: 610px;
        left: 50%;
        color: #0d19ff;
        background: #00000000;
        height: 41px;
        font-weight: 700;
    }
}
</style>
<?php
if ( 1 < $this->crannyProperty['buildingCount'] )
{
 ?>
<br/><b><?php echo LANGUI_CUSTBU_CRANNYEXTRA; ?>
 : <?php echo $this->crannyProperty['totalSize']; ?>
 <?php echo constant( "item_unit_".$this->buildProperties['building']['item_id'] ); ?>
</b><?php } ?>
