<style>
@media screen and (max-width: 900px) {
    .molvp-protection {
        position: absolute;
        display: none;
        z-index: 100;
        float: right;
        top: 610px;
        left: 50%;
        color: #0d19ff;
        background: #00000000;
        height: 41px;
        font-weight: 700;
    }
}
</style>
<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />  
<center><br>تم إغلاق باب النشر
<br><br>اذا كنت تري ان هناك مشكلة لا تتردد فى مراسلتنا.
<br><br><a href="village1.php">اضغط هنا للرجوع للعبة
<br><br><a href="support.php">اضغط هنا لمراسلة الدعم
</body>
</html>