<style>
@media screen and (max-width: 900px) {
    .molvp-protection {
        position: absolute;
        display: none;
        z-index: 100;
        float: right;
        top: 610px;
        left: 50%;
        color: #0d19ff;
        background: #00000000;
        height: 41px;
        font-weight: 700;
    }
}
</style>
<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>
<body>
<?php
  echo "<h1><img src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" class=\"passwort\" alt=\"";
  echo LANGUI_PWD_T1;
  echo "\"></h1>\r\n<h5><img src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" class=\"img_u22\" alt=\"";
  echo LANGUI_PWD_T2;
  echo "\"></h5>\r\n";
  if ($this->pageState == 1) {
      echo "<p>";
      echo LANGUI_PWD_T3;
      echo "</p>\r\n<form action=\"password\" method=\"post\">\r\n\t<p>\r\n\t\t<b>";
      echo LANGUI_PWD_T4;
      echo "</b><br>\r\n\t\t<input type=\"hidden\" name=\"id\" value=\"";
      echo $this->playerId;
      echo "\">\r\n\t\t<input class=\"text\" type=\"text\" name=\"email\" maxlength=\"50\">\r\n\t</p>\r\n\t<p>\r\n\t\t<input type=\"image\" value=\"ok\" name=\"s1\" src=\"".$GLOBALS['AppConfig']['system']['linksite']."x.gif\" class=\"dynamic_img\" id=\"btn_ok\" alt=\"";
      echo text_okdone_lang;
      echo "\">\r\n\t</p>\r\n</form>\r\n";
  } else if ($this->pageState == 2) {
      echo LANGUI_PWD_T5;
  } else if ($this->pageState == 3) {
      echo LANGUI_PWD_T6;
  } else if ($this->pageState == 4) {
      echo LANGUI_PWD_T7;
  } else if ($this->pageState == 5) {
      echo LANGUI_PWD_T8;
  }
?>

</body>
</html>